//
//  ChoiceGraph+LazyComputation.swift
//  Exhaust
//

// MARK: - Lazy Edge Computation

extension ChoiceGraph {
    /// Computes type-compatibility edges grouped by parent decision context.
    ///
    /// Redistribution moves value mass between two leaves within a single decision context. Two structural cases qualify:
    ///
    /// 1. **Sequence siblings** — chooseBits children of the same sequence parent. Only emitted for heterogeneous sequences (``SequenceMetadata/elementTypeTag`` is nil). Homogeneous sequences are handled by ``homogeneousRedistributionPairs(graph:innerDescendantToBind:)`` in O(C log C) instead of O(C^2).
    /// 2. **Zip cross-slot** — chooseBits descendants of *different* children of a common zip parent. Tuple slots are simultaneously chosen and the property frequently correlates their values; redistribution between them is the only way to reduce to a coupled extremum. Bound5's `d + e == -32769` constraint is the canonical example. Cross-slot pairs between two homogeneous sequences of the same type are also deferred to the homogeneous pair path.
    ///
    /// Cross-parent pairs whose lowest common ancestor is a sequence (the elements of a `[[Int]]` workload) are *not* generated. Sequence elements are independently chosen and the property treats them as independent decision contexts; cross-element redistribution produces no reduction-meaningful candidates and balloons the edge count quadratically for high-fanout sequences.
    ///
    /// ## Complexity
    ///
    /// Pass 1 is O(C^2) per *heterogeneous* sequence parent only. Homogeneous sequences (the common case) are skipped. Pass 2 is Sigma(L_i * L_j) for cross-zip pairs, skipping pairs between two homogeneous groups of the same type.
    func computeTypeCompatibilityEdges() -> [TypeCompatibilityEdge] {
        var edges: [TypeCompatibilityEdge] = []

        // Pass 1: chooseBits siblings under each heterogeneous sequence parent.
        // Homogeneous sequences (elementTypeTag != nil) are handled by homogeneousRedistributionPairs() in O(C log C) instead of O(C²).
        for parentNodeID in liveNodeIDs {
            let parentNode = nodes[parentNodeID]
            guard case let .sequence(seqMetadata) = parentNode.kind else { continue }
            guard seqMetadata.elementTypeTag == nil else { continue }

            var siblings: [(nodeID: Int, tag: TypeTag)] = []
            siblings.reserveCapacity(parentNode.children.count)
            for childID in parentNode.children {
                guard childID < nodes.count else { continue }
                let child = nodes[childID]
                guard child.positionRange != nil else { continue }
                guard case let .chooseBits(metadata) = child.kind else { continue }
                siblings.append((nodeID: childID, tag: metadata.typeTag))
            }
            guard siblings.count >= 2 else { continue }

            var indexA = 0
            while indexA < siblings.count {
                let limit = min(siblings.count, indexA + 1 + SchedulerTuning.maxPairLookahead)
                var indexB = indexA + 1
                while indexB < limit {
                    let tagA = siblings[indexA].tag
                    let tagB = siblings[indexB].tag
                    let sharedTag: TypeTag? = (tagA == tagB) ? tagA : nil
                    edges.append(TypeCompatibilityEdge(
                        nodeA: siblings[indexA].nodeID,
                        nodeB: siblings[indexB].nodeID,
                        typeTag: sharedTag
                    ))
                    indexB += 1
                }
                indexA += 1
            }
        }

        // Pass 2: chooseBits descendants across different children of each zip parent.
        // Tuple slots are simultaneously chosen, so cross-slot value pairs are semantically meaningful redistribution candidates (Bound5's d + e coupling). Within-slot pairs are skipped here because they were (or will be) generated by pass 1 against the appropriate sequence parent inside that slot.
        for zipNodeID in liveNodeIDs {
            let zipNode = nodes[zipNodeID]
            guard case .zip = zipNode.kind else { continue }
            guard zipNode.children.count >= 2 else { continue }

            // Collect leaves per zip child via a containment-tree walk.
            // Track each child's homogeneous type tag (if any) so that cross-slot pairs between two homogeneous groups of the same type can be deferred to homogeneousRedistributionPairs().
            var perChildLeaves: [[(nodeID: Int, tag: TypeTag)]] = []
            var perChildHomogeneousTag: [TypeTag?] = []
            perChildLeaves.reserveCapacity(zipNode.children.count)
            perChildHomogeneousTag.reserveCapacity(zipNode.children.count)
            for childID in zipNode.children {
                var leaves: [(nodeID: Int, tag: TypeTag)] = []
                collectChooseBitsDescendants(rootID: childID, into: &leaves)
                perChildLeaves.append(leaves)
                let childNode = nodes[childID]
                if case let .sequence(seqMeta) = childNode.kind {
                    perChildHomogeneousTag.append(seqMeta.elementTypeTag)
                } else {
                    perChildHomogeneousTag.append(nil)
                }
            }

            // Pair leaves across different child groups only. Skip pairs between two homogeneous groups of the same type — those are handled by homogeneousRedistributionPairs() in O(C) instead of O(L_i * L_j).
            var groupA = 0
            while groupA < perChildLeaves.count {
                var groupB = groupA + 1
                while groupB < perChildLeaves.count {
                    let tagA = perChildHomogeneousTag[groupA]
                    let tagB = perChildHomogeneousTag[groupB]
                    if let tagA, let tagB, tagA == tagB {
                        groupB += 1
                        continue
                    }
                    let leafLimit = SchedulerTuning.maxPairLookahead
                    for (indexA, leafA) in perChildLeaves[groupA].enumerated() {
                        let bLimit = min(perChildLeaves[groupB].count, leafLimit)
                        for indexB in 0 ..< bLimit {
                            let leafB = perChildLeaves[groupB][indexB]
                            let sharedTag: TypeTag? = (leafA.tag == leafB.tag) ? leafA.tag : nil
                            edges.append(TypeCompatibilityEdge(
                                nodeA: leafA.nodeID,
                                nodeB: leafB.nodeID,
                                typeTag: sharedTag
                            ))
                        }
                        if indexA >= leafLimit { break }
                    }
                    groupB += 1
                }
                groupA += 1
            }
        }

        return edges
    }

    /// Walks the containment tree under `rootID` and appends every active chooseBits descendant to `result`. Used by ``computeTypeCompatibilityEdges()`` to gather leaves per zip child for cross-slot pairing.
    private func collectChooseBitsDescendants(
        rootID: Int,
        into result: inout [(nodeID: Int, tag: TypeTag)]
    ) {
        guard rootID < nodes.count else { return }
        let node = nodes[rootID]
        guard node.positionRange != nil else { return }
        if case let .chooseBits(metadata) = node.kind {
            result.append((nodeID: rootID, tag: metadata.typeTag))
        }
        for childID in node.children {
            collectChooseBitsDescendants(rootID: childID, into: &result)
        }
    }

    // MARK: - On-Demand Reachability

    /// Returns true when `target` is reachable from `source` via one or more dependency edges.
    ///
    /// Uses a DFS through the cached ``dependencyAdjacency`` list, stopping as soon as `target` is found.
    func isReachable(from source: Int, to target: Int) -> Bool {
        guard source < nodes.count, target < nodes.count else { return false }
        let adjacency = dependencyAdjacency
        var visited = Set<Int>()
        var stack = [source]
        while let current = stack.popLast() {
            guard visited.insert(current).inserted else { continue }
            for neighbour in adjacency[current] {
                if neighbour == target { return true }
                stack.append(neighbour)
            }
        }
        return false
    }

    /// Returns the subset of `candidates` reachable from `source` via dependency edges.
    ///
    /// Runs a single DFS from `source` and collects intersections with the candidate set. Used by ``deletionAntichain`` to build the restricted reachability relation over antichain candidates without computing the full transitive closure.
    ///
    /// - Complexity: O(V + E) per call.
    func reachableNodes(from source: Int, within candidates: Set<Int>) -> Set<Int> {
        guard source < nodes.count else { return [] }
        let adjacency = dependencyAdjacency
        var visited = Set<Int>()
        var result = Set<Int>()
        var stack = [source]
        while let current = stack.popLast() {
            guard visited.insert(current).inserted else { continue }
            if current != source, candidates.contains(current) {
                result.insert(current)
            }
            for neighbour in adjacency[current] {
                stack.append(neighbour)
            }
        }
        return result
    }
}
