/// Operations for making choices and generating random values within ranges.
/// These combinators handle weighted selection and bounded value generation.
public extension Gen {
    /// Creates a generator that randomly selects from multiple weighted options.
    ///
    /// This combinator enables probabilistic generation where different outcomes
    /// have different likelihoods. The weights don't need to sum to any particular
    /// value - they're interpreted as relative frequencies.
    ///
    /// During shrinking, the system will try simpler choices first based on their
    /// position in the choices array and their weights.
    ///
    /// - Parameter choices: An array of (weight, generator) pairs. Must not be empty.
    /// - Returns: A generator that produces values from one of the provided generators
    /// - Precondition: At least one choice must be provided
    @inlinable
    static func pick<Output>(
        choices: [(weight: UInt64, generator: ReflectiveGenerator<Output>)]
    ) -> ReflectiveGenerator<Output> {
        precondition(choices.isEmpty == false, "At least one choice must be provided")
        // The nested generators must all have the same Output type.
        // We erase it to `Any` for the operation, but the `liftF` call
        // ensures the final monad has the correct `Output` type.
        var array = ContiguousArray<ReflectiveOperation.PickTuple>()
        array.reserveCapacity(choices.count)

        for index in choices.indices {
            let choice = choices[index]
            array.append((
                weight: choice.weight,
                label: UInt64(index) + 1,
                generator: choice.generator.erase()
            ))
        }
        return liftF(.pick(choices: array))
    }
    
    /// Creates a generator that randomly selects from multiple weighted options.
    ///
    /// This combinator enables probabilistic generation where different outcomes
    /// have different likelihoods. The weights don't need to sum to any particular
    /// value - they're interpreted as relative frequencies.
    ///
    /// During shrinking, the system will try simpler choices first based on their
    /// position in the choices array and their weights.
    ///
    /// - Parameter choices: An array of (weight, generator) pairs. Must not be empty.
    /// - Returns: A generator that produces values from one of the provided generators
    /// - Precondition: At least one choice must be provided
    @inlinable
    static func pick<Output>(
        choices: [(weight: Int, generator: ReflectiveGenerator<Output>)]
    ) -> ReflectiveGenerator<Output> {
        precondition(choices.map(\.weight).allSatisfy { $0 > 0 }, "Weights must be higher than zero")
        
        return pick(choices: choices.map { (UInt64($0.weight), $0.generator) })
    }
    
    /// Generates a random character from a specified bit pattern range.
    ///
    /// Characters are generated by selecting random bit patterns and converting them
    /// to valid Unicode characters. This approach ensures uniform distribution across
    /// the character space while respecting Unicode validity constraints.
    ///
    /// - Parameter range: The bit pattern range to generate from. Defaults to the first range in Character.bitPatternRanges
    /// - Returns: A generator that produces random characters
    @inlinable
    static func chooseCharacter(in range: ClosedRange<UInt64>? = nil) -> ReflectiveGenerator<Character> {
        // Default to the lower range
        let actualRange = range ?? Character.bitPatternRanges[0]
        let operation = ReflectiveOperation.chooseBits(
            min: actualRange.lowerBound,
            max: actualRange.upperBound,
            tag: .character
        )
        
        return .impure(operation: operation) { result in
            if let character = result as? UInt64 {
                return .pure(Character(bitPattern64: character))
            } else if let character = result as? Character {
                // Not sure this is ever hit
                return .pure(character)
            } else if let optional = result as? Optional<Character>, optional == nil {
                throw Interpreters.ReflectionError.reflectedNil(type: String(describing: Character.self))
            } else {
                throw GeneratorError.typeMismatch(expected: "Character", actual: String(describing: type(of: result)))
            }
        }
    }
    
    /// Generates a random value within a specified range for types conforming to BitPatternConvertible.
    ///
    /// This is the primary method for generating bounded random values. It works by
    /// converting the range bounds to bit patterns, generating a random bit pattern
    /// within those bounds, then converting back to the target type.
    ///
    /// The type parameter allows the compiler to infer the return type, while the range
    /// parameter controls the bounds. If no range is provided, the full range for the
    /// type is used.
    ///
    /// - Parameters:
    ///   - range: The range of values to generate from. Defaults to the type's full range
    ///   - type: The output type to generate. Usually inferred from context
    /// - Returns: A generator that produces random values of the specified type within the range
    @inlinable
    static func choose<Output: BitPatternConvertible>(
        in range: ClosedRange<Output>? = nil, 
        type: Output.Type = Output.self
    ) -> ReflectiveGenerator<Output> {
        let minBits = range?.lowerBound.bitPattern64 ?? Output.bitPatternRanges[0].lowerBound
        let maxBits = range?.upperBound.bitPattern64 ?? Output.bitPatternRanges[0].upperBound
        let tag = Output.tag
        
        return .impure(operation: .chooseBits(min: minBits, max: maxBits, tag: tag)) { result in
            switch tag {
            case .uint64:
                // This catches [Character] and String
                if let sequence = result as? any Sequence {
                    return .pure(UInt64(sequence.underestimatedCount) as! Output)
                }
                fallthrough
//                return .pure(result as! Output)
            default:
                guard let convertible = result as? any BitPatternConvertible else {
                    throw GeneratorError.typeMismatch(
                        expected: "any BitPatternConvertible",
                        actual: String(describing: Swift.type(of: result))
                    )
                }
                return .pure(Output(bitPattern64: convertible.bitPattern64))
            }
        }
    }
}
